name: Deploy to Github Pages

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run predeploy
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/voces/browser
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
          commit-message: "ci: deploy ${{ github.ref_name }}"
