name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        type: string
        default: "patch"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: git config --local user.name "github-actions[bot]"
      - run: git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm version ${{ inputs.version }} --tag-version-prefix ""
      - run: git push --follow-tags
